version: "3"

services:
  nginx:
    build: ./docker/nginx
    container_name: "e3logi-try-nginx"
    ports:
      - "8081:80"
    restart: always
    volumes:
      - ./src:/var/www
    depends_on:
      - php-fpm
  php-fpm:
    build: ./docker/php-fpm
    container_name: "e3logi-try-php-fpm"
    restart: always
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    links:
      - mysql
    depends_on:
      - mysql
  composer:
    image: composer:1.8
    container_name: "e3logi-try-composer"
    volumes:
      - ./src:/var/www
    working_dir: /var/www
  mysql:
    image: mysql:5.7
    container_name: "e3logi-try-mysql"
    ports:
      - 43306:3306
    restart: always
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: e3logi-try-db
      MYSQL_USER: e3logi-try-user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
